### ISSUE TITLE
Multiple hover play and paused

### ISSUE THREAD

**Issue by dngraphisme** [Gyanreyer/hover-video-player#3]
Hello @Gyanreyer,

Thank you for this library :)

I'm trying to do something but I can't do it with your doc.

I would like to put play and paused each time a link is hovered over a class for example.

But I have the impression that this does not work :

```
const player = document.querySelector("hover-video-player");

        $(".site-navigation li.page_item").each(function () {
            $(this).on("mouseenter", function () {
                player.playbackState = "play";
            })
            $(this).on("mouseenter", function () {
                player.playbackState = "paused";
            })
        });
```

I only have this that works:

`hover-target=""`

But in the end it is not practical if you want to hover over several links. I don't have any additional IDs on my hrefs.

Thanks for your return

**Comment by Gyanreyer** [comment]
Thank you for reaching out, this is a great question! Currently I don't think there's a good supported way to have multiple hover targets for a single hover-video-player instance.

I think it's very reasonable to expect that feature to exist though, so I'll take a look today and see if I can come up with a good solution.

**Comment by Gyanreyer** [comment]
Hello! If you update to v1.1.0, I just added support for multiple hover targets. Based on your example, you should be able to do this now:

```html
<hover-video-player hover-target=".site-navigation li.page_item">
  ...
</hover-video-player>
```

`player.hoverTarget` will now also accept iterables of `Element` instances, so this would also work:
```js
player.hoverTarget = document.querySelectorAll(".site-navigation li.page_item");
```

Let me know if you have any questions or run into any issues!

**Comment by dngraphisme** [comment]
Hello @Gyanreyer beautiful ! I'll test this as soon as possible and let you know if it's ok :) Thank you very much !
